// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"golang/handler"
)

// Injectors from wire.go:

func Initialize(msg string) handler.DeptsHandler {
	deptsHandler := handler.NewDeptsHandler(msg)
	return deptsHandler
}
